#!/bin/bash
# Quick setup script for IIC Authentication Server

echo "🚀 IIC Authentication Server Setup"
echo "=================================="
echo ""

echo "📋 Prerequisites Check:"
echo "  ✅ Python 3.8+ (using UV)"
echo "  ✅ FastAPI and dependencies installed"
echo "  ⚠️  PostgreSQL database required"
echo ""

echo "🔧 Next Steps:"
echo ""
echo "1. Install and start PostgreSQL:"
echo "   brew install postgresql"
echo "   brew services start postgresql"
echo ""
echo "2. Create database:"
echo "   psql postgres"
echo "   CREATE DATABASE iic_auth;"
echo "   CREATE USER postgres WITH PASSWORD 'password';"
echo "   GRANT ALL PRIVILEGES ON DATABASE iic_auth TO postgres;"
echo "   \\q"
echo ""
echo "3. Update database configuration in .env file if needed"
echo ""
echo "4. Initialize database and create admin user:"
echo "   uv run python init_db.py"
echo ""
echo "5. (Optional) Create sample users for testing:"
echo "   uv run python create_sample_users.py"
echo ""
echo "6. Start the server:"
echo "   uv run python main.py"
echo "   # or"
echo "   uv run python start_server.py"
echo ""
echo "7. Access the API:"
echo "   🌐 API: http://localhost:8000"
echo "   📚 Docs: http://localhost:8000/docs"
echo ""
echo "🔐 Default Admin Credentials:"
echo "   Username: admin"
echo "   Password: admin123"
echo "   ⚠️  Change this password after first login!"
echo ""
echo "📖 For detailed instructions, see README.md"
echo ""
